project_name: traefik-migration

builds:
  - binary: traefik-migration
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
#      - 386

archives:
  - id: faekeapi
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - readme.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

release:
  disable: true
